version: '3.4'

services:
  pithyurl_redis:
    container_name: pithyurl_redis
    build:
      context: ./redis
      dockerfile: ./Dockerfile
    ports:
      - "6379:6379"
    networks:
      - pithyurl_network
    volumes:
      - redis_data:/data
      
  pithyurl:
    image: pithyurl
    build:
      context: .
      dockerfile: ./Dockerfile
